namespace :plant_list do
  desc 'Handles interacting with plant list'

  task fetch: :environment do
    require 'open-uri'

    %w(
      http://www.theplantlist.org/browse/A/Acanthaceae/Acanthaceae.csv
      http://www.theplantlist.org/browse/A/Achariaceae/Achariaceae.csv
      http://www.theplantlist.org/browse/A/Achatocarpaceae/Achatocarpaceae.csv
      http://www.theplantlist.org/browse/A/Acoraceae/Acoraceae.csv
      http://www.theplantlist.org/browse/B/Acrobolbaceae/Acrobolbaceae.csv
      http://www.theplantlist.org/browse/A/Actinidiaceae/Actinidiaceae.csv
      http://www.theplantlist.org/browse/B/Adelanthaceae/Adelanthaceae.csv
      http://www.theplantlist.org/browse/P/Adiantaceae/Adiantaceae.csv
      http://www.theplantlist.org/browse/A/Adoxaceae/Adoxaceae.csv
      http://www.theplantlist.org/browse/A/Aextoxicaceae/Aextoxicaceae.csv
      http://www.theplantlist.org/browse/A/Aizoaceae/Aizoaceae.csv
      http://www.theplantlist.org/browse/A/Akaniaceae/Akaniaceae.csv
      http://www.theplantlist.org/browse/A/Alismataceae/Alismataceae.csv
      http://www.theplantlist.org/browse/B/Allisoniaceae/Allisoniaceae.csv
      http://www.theplantlist.org/browse/A/Alseuosmiaceae/Alseuosmiaceae.csv
      http://www.theplantlist.org/browse/A/Alstroemeriaceae/Alstroemeriaceae.csv
      http://www.theplantlist.org/browse/A/Altingiaceae/Altingiaceae.csv
      http://www.theplantlist.org/browse/A/Alzateaceae/Alzateaceae.csv
      http://www.theplantlist.org/browse/A/Amaranthaceae/Amaranthaceae.csv
      http://www.theplantlist.org/browse/A/Amaryllidaceae/Amaryllidaceae.csv
      http://www.theplantlist.org/browse/B/Amblystegiaceae/Amblystegiaceae.csv
      http://www.theplantlist.org/browse/A/Amborellaceae/Amborellaceae.csv
      http://www.theplantlist.org/browse/A/Anacardiaceae/Anacardiaceae.csv
      http://www.theplantlist.org/browse/A/Anarthriaceae/Anarthriaceae.csv
      http://www.theplantlist.org/browse/B/Anastrophyllaceae/Anastrophyllaceae.csv
      http://www.theplantlist.org/browse/A/Ancistrocladaceae/Ancistrocladaceae.csv
      http://www.theplantlist.org/browse/B/Andreaeaceae/Andreaeaceae.csv
      http://www.theplantlist.org/browse/B/Aneuraceae/Aneuraceae.csv
      http://www.theplantlist.org/browse/A/Anisophylleaceae/Anisophylleaceae.csv
      http://www.theplantlist.org/browse/A/Annonaceae/Annonaceae.csv
      http://www.theplantlist.org/browse/B/Antheliaceae/Antheliaceae.csv
      http://www.theplantlist.org/browse/B/Anthocerotaceae/Anthocerotaceae.csv
      http://www.theplantlist.org/browse/A/Aphanopetalaceae/Aphanopetalaceae.csv
      http://www.theplantlist.org/browse/A/Aphloiaceae/Aphloiaceae.csv
      http://www.theplantlist.org/browse/A/Apiaceae/Apiaceae.csv
      http://www.theplantlist.org/browse/A/Apocynaceae/Apocynaceae.csv
      http://www.theplantlist.org/browse/A/Apodanthaceae/Apodanthaceae.csv
      http://www.theplantlist.org/browse/A/Aponogetonaceae/Aponogetonaceae.csv
      http://www.theplantlist.org/browse/A/Aquifoliaceae/Aquifoliaceae.csv
      http://www.theplantlist.org/browse/A/Araceae/Araceae.csv
      http://www.theplantlist.org/browse/A/Araliaceae/Araliaceae.csv
      http://www.theplantlist.org/browse/G/Araucariaceae/Araucariaceae.csv
      http://www.theplantlist.org/browse/B/Archidiaceae/Archidiaceae.csv
      http://www.theplantlist.org/browse/A/Arecaceae/Arecaceae.csv
      http://www.theplantlist.org/browse/A/Argophyllaceae/Argophyllaceae.csv
      http://www.theplantlist.org/browse/A/Aristolochiaceae/Aristolochiaceae.csv
      http://www.theplantlist.org/browse/B/Arnelliaceae/Arnelliaceae.csv
      http://www.theplantlist.org/browse/A/Asparagaceae/Asparagaceae.csv
      http://www.theplantlist.org/browse/P/Aspleniaceae/Aspleniaceae.csv
      http://www.theplantlist.org/browse/A/Asteliaceae/Asteliaceae.csv
      http://www.theplantlist.org/browse/A/Asteropeiaceae/Asteropeiaceae.csv
      http://www.theplantlist.org/browse/A/Atherospermataceae/Atherospermataceae.csv
      http://www.theplantlist.org/browse/B/Aulacomniaceae/Aulacomniaceae.csv
      http://www.theplantlist.org/browse/A/Austrobaileyaceae/Austrobaileyaceae.csv
      http://www.theplantlist.org/browse/B/Aytoniaceae/Aytoniaceae.csv
      http://www.theplantlist.org/browse/A/Balanopaceae/Balanopaceae.csv
      http://www.theplantlist.org/browse/A/Balanophoraceae/Balanophoraceae.csv
      http://www.theplantlist.org/browse/B/Balantiopsaceae/Balantiopsaceae.csv
      http://www.theplantlist.org/browse/A/Balsaminaceae/Balsaminaceae.csv
      http://www.theplantlist.org/browse/A/Barbeuiaceae/Barbeuiaceae.csv
      http://www.theplantlist.org/browse/A/Barbeyaceae/Barbeyaceae.csv
      http://www.theplantlist.org/browse/B/Bartramiaceae/Bartramiaceae.csv
      http://www.theplantlist.org/browse/A/Basellaceae/Basellaceae.csv
      http://www.theplantlist.org/browse/A/Bataceae/Bataceae.csv
      http://www.theplantlist.org/browse/A/Begoniaceae/Begoniaceae.csv
      http://www.theplantlist.org/browse/A/Berberidaceae/Berberidaceae.csv
      http://www.theplantlist.org/browse/A/Berberidopsidaceae/Berberidopsidaceae.csv
      http://www.theplantlist.org/browse/A/Betulaceae/Betulaceae.csv
      http://www.theplantlist.org/browse/A/Biebersteiniaceae/Biebersteiniaceae.csv
      http://www.theplantlist.org/browse/A/Bignoniaceae/Bignoniaceae.csv
      http://www.theplantlist.org/browse/A/Bixaceae/Bixaceae.csv
      http://www.theplantlist.org/browse/A/Blandfordiaceae/Blandfordiaceae.csv
      http://www.theplantlist.org/browse/P/Blechnaceae/Blechnaceae.csv
      http://www.theplantlist.org/browse/A/Bonnetiaceae/Bonnetiaceae.csv
      http://www.theplantlist.org/browse/A/Boraginaceae/Boraginaceae.csv
      http://www.theplantlist.org/browse/A/Boryaceae/Boryaceae.csv
      http://www.theplantlist.org/browse/G/Boweniaceae/Boweniaceae.csv
      http://www.theplantlist.org/browse/B/Brachytheciaceae/Brachytheciaceae.csv
      http://www.theplantlist.org/browse/A/Brassicaceae/Brassicaceae.csv
      http://www.theplantlist.org/browse/B/Brevianthaceae/Brevianthaceae.csv
      http://www.theplantlist.org/browse/A/Bromeliaceae/Bromeliaceae.csv
      http://www.theplantlist.org/browse/B/Bruchiaceae/Bruchiaceae.csv
      http://www.theplantlist.org/browse/A/Brunelliaceae/Brunelliaceae.csv
      http://www.theplantlist.org/browse/A/Bruniaceae/Bruniaceae.csv
      http://www.theplantlist.org/browse/B/Bryaceae/Bryaceae.csv
      http://www.theplantlist.org/browse/B/Bryobartramiaceae/Bryobartramiaceae.csv
      http://www.theplantlist.org/browse/B/Bryoxiphiaceae/Bryoxiphiaceae.csv
      http://www.theplantlist.org/browse/A/Burmanniaceae/Burmanniaceae.csv
      http://www.theplantlist.org/browse/A/Burseraceae/Burseraceae.csv
      http://www.theplantlist.org/browse/A/Butomaceae/Butomaceae.csv
      http://www.theplantlist.org/browse/A/Buxaceae/Buxaceae.csv
      http://www.theplantlist.org/browse/B/Buxbaumiaceae/Buxbaumiaceae.csv
      http://www.theplantlist.org/browse/A/Byblidaceae/Byblidaceae.csv
      http://www.theplantlist.org/browse/A/Cabombaceae/Cabombaceae.csv
      http://www.theplantlist.org/browse/A/Cactaceae/Cactaceae.csv
      http://www.theplantlist.org/browse/A/Calceolariaceae/Calceolariaceae.csv
      http://www.theplantlist.org/browse/B/Calomniaceae/Calomniaceae.csv
      http://www.theplantlist.org/browse/A/Calophyllaceae/Calophyllaceae.csv
      http://www.theplantlist.org/browse/A/Calycanthaceae/Calycanthaceae.csv
      http://www.theplantlist.org/browse/A/Calyceraceae/Calyceraceae.csv
      http://www.theplantlist.org/browse/B/Calymperaceae/Calymperaceae.csv
      http://www.theplantlist.org/browse/B/Calypogeiaceae/Calypogeiaceae.csv
      http://www.theplantlist.org/browse/A/Campanulaceae/Campanulaceae.csv
      http://www.theplantlist.org/browse/A/Campyneumataceae/Campyneumataceae.csv
      http://www.theplantlist.org/browse/A/Canellaceae/Canellaceae.csv
      http://www.theplantlist.org/browse/A/Cannabaceae/Cannabaceae.csv
      http://www.theplantlist.org/browse/A/Cannaceae/Cannaceae.csv
      http://www.theplantlist.org/browse/A/Capparaceae/Capparaceae.csv
      http://www.theplantlist.org/browse/A/Caprifoliaceae/Caprifoliaceae.csv
      http://www.theplantlist.org/browse/A/Cardiopteridaceae/Cardiopteridaceae.csv
      http://www.theplantlist.org/browse/A/Caricaceae/Caricaceae.csv
      http://www.theplantlist.org/browse/A/Carlemanniaceae/Carlemanniaceae.csv
      http://www.theplantlist.org/browse/A/Caryocaraceae/Caryocaraceae.csv
      http://www.theplantlist.org/browse/A/Caryophyllaceae/Caryophyllaceae.csv
      http://www.theplantlist.org/browse/A/Casuarinaceae/Casuarinaceae.csv
      http://www.theplantlist.org/browse/B/Catagoniaceae/Catagoniaceae.csv
      http://www.theplantlist.org/browse/B/Catoscopiaceae/Catoscopiaceae.csv
      http://www.theplantlist.org/browse/A/Celastraceae/Celastraceae.csv
      http://www.theplantlist.org/browse/A/Centrolepidaceae/Centrolepidaceae.csv
      http://www.theplantlist.org/browse/A/Centroplacaceae/Centroplacaceae.csv
      http://www.theplantlist.org/browse/A/Cephalotaceae/Cephalotaceae.csv
      http://www.theplantlist.org/browse/G/Cephalotaxaceae/Cephalotaxaceae.csv
      http://www.theplantlist.org/browse/B/Cephaloziaceae/Cephaloziaceae.csv
      http://www.theplantlist.org/browse/B/Cephaloziellaceae/Cephaloziellaceae.csv
      http://www.theplantlist.org/browse/A/Ceratophyllaceae/Ceratophyllaceae.csv
      http://www.theplantlist.org/browse/A/Cercidiphyllaceae/Cercidiphyllaceae.csv
      http://www.theplantlist.org/browse/B/Chaetophyllopsaceae/Chaetophyllopsaceae.csv
      http://www.theplantlist.org/browse/A/Chloranthaceae/Chloranthaceae.csv
      http://www.theplantlist.org/browse/B/Chonecoleaceae/Chonecoleaceae.csv
      http://www.theplantlist.org/browse/A/Chrysobalanaceae/Chrysobalanaceae.csv
      http://www.theplantlist.org/browse/B/Cinclidotaceae/Cinclidotaceae.csv
      http://www.theplantlist.org/browse/A/Circaeasteraceae/Circaeasteraceae.csv
      http://www.theplantlist.org/browse/A/Cistaceae/Cistaceae.csv
      http://www.theplantlist.org/browse/A/Cleomaceae/Cleomaceae.csv
      http://www.theplantlist.org/browse/A/Clethraceae/Clethraceae.csv
      http://www.theplantlist.org/browse/B/Cleveaceae/Cleveaceae.csv
      http://www.theplantlist.org/browse/B/Climaciaceae/Climaciaceae.csv
      http://www.theplantlist.org/browse/A/Clusiaceae/Clusiaceae.csv
      http://www.theplantlist.org/browse/A/Colchicaceae/Colchicaceae.csv
      http://www.theplantlist.org/browse/A/Columelliaceae/Columelliaceae.csv
      http://www.theplantlist.org/browse/A/Combretaceae/Combretaceae.csv
      http://www.theplantlist.org/browse/A/Commelinaceae/Commelinaceae.csv
      http://www.theplantlist.org/browse/A/Compositae/Compositae.csv
      http://www.theplantlist.org/browse/A/Connaraceae/Connaraceae.csv
      http://www.theplantlist.org/browse/B/Conocephalaceae/Conocephalaceae.csv
      http://www.theplantlist.org/browse/A/Convolvulaceae/Convolvulaceae.csv
      http://www.theplantlist.org/browse/A/Coriariaceae/Coriariaceae.csv
      http://www.theplantlist.org/browse/A/Cornaceae/Cornaceae.csv
      http://www.theplantlist.org/browse/A/Corsiaceae/Corsiaceae.csv
      http://www.theplantlist.org/browse/B/Corsiniaceae/Corsiniaceae.csv
      http://www.theplantlist.org/browse/A/Corynocarpaceae/Corynocarpaceae.csv
      http://www.theplantlist.org/browse/A/Costaceae/Costaceae.csv
      http://www.theplantlist.org/browse/A/Crassulaceae/Crassulaceae.csv
      http://www.theplantlist.org/browse/A/Crossosomataceae/Crossosomataceae.csv
      http://www.theplantlist.org/browse/B/Cryphaeaceae/Cryphaeaceae.csv
      http://www.theplantlist.org/browse/A/Crypteroniaceae/Crypteroniaceae.csv
      http://www.theplantlist.org/browse/A/Ctenolophonaceae/Ctenolophonaceae.csv
      http://www.theplantlist.org/browse/A/Cucurbitaceae/Cucurbitaceae.csv
      http://www.theplantlist.org/browse/A/Cunoniaceae/Cunoniaceae.csv
      http://www.theplantlist.org/browse/G/Cupressaceae/Cupressaceae.csv
      http://www.theplantlist.org/browse/A/Curtisiaceae/Curtisiaceae.csv
      http://www.theplantlist.org/browse/P/Cyatheaceae/Cyatheaceae.csv
      http://www.theplantlist.org/browse/G/Cycadaceae/Cycadaceae.csv
      http://www.theplantlist.org/browse/A/Cyclanthaceae/Cyclanthaceae.csv
      http://www.theplantlist.org/browse/A/Cymodoceaceae/Cymodoceaceae.csv
      http://www.theplantlist.org/browse/A/Cynomoriaceae/Cynomoriaceae.csv
      http://www.theplantlist.org/browse/A/Cyperaceae/Cyperaceae.csv
      http://www.theplantlist.org/browse/A/Cyrillaceae/Cyrillaceae.csv
      http://www.theplantlist.org/browse/B/Cyrtopodaceae/Cyrtopodaceae.csv
      http://www.theplantlist.org/browse/A/Cytinaceae/Cytinaceae.csv
      http://www.theplantlist.org/browse/B/Daltoniaceae/Daltoniaceae.csv
      http://www.theplantlist.org/browse/A/Daphniphyllaceae/Daphniphyllaceae.csv
      http://www.theplantlist.org/browse/A/Dasypogonaceae/Dasypogonaceae.csv
      http://www.theplantlist.org/browse/A/Datiscaceae/Datiscaceae.csv
      http://www.theplantlist.org/browse/P/Davalliaceae/Davalliaceae.csv
      http://www.theplantlist.org/browse/A/Degeneriaceae/Degeneriaceae.csv
      http://www.theplantlist.org/browse/B/Dendrocerotaceae/Dendrocerotaceae.csv
      http://www.theplantlist.org/browse/P/Dennstaedtiaceae/Dennstaedtiaceae.csv
      http://www.theplantlist.org/browse/A/Diapensiaceae/Diapensiaceae.csv
      http://www.theplantlist.org/browse/A/Dichapetalaceae/Dichapetalaceae.csv
      http://www.theplantlist.org/browse/P/Dicksoniaceae/Dicksoniaceae.csv
      http://www.theplantlist.org/browse/B/Dicnemonaceae/Dicnemonaceae.csv
      http://www.theplantlist.org/browse/B/Dicranaceae/Dicranaceae.csv
      http://www.theplantlist.org/browse/A/Didiereaceae/Didiereaceae.csv
      http://www.theplantlist.org/browse/A/Dilleniaceae/Dilleniaceae.csv
      http://www.theplantlist.org/browse/A/Dioncophyllaceae/Dioncophyllaceae.csv
      http://www.theplantlist.org/browse/A/Dioscoreaceae/Dioscoreaceae.csv
      http://www.theplantlist.org/browse/A/Dipentodontaceae/Dipentodontaceae.csv
      http://www.theplantlist.org/browse/P/Dipteridaceae/Dipteridaceae.csv
      http://www.theplantlist.org/browse/A/Dipterocarpaceae/Dipterocarpaceae.csv
      http://www.theplantlist.org/browse/A/Dirachmaceae/Dirachmaceae.csv
      http://www.theplantlist.org/browse/B/Disceliaceae/Disceliaceae.csv
      http://www.theplantlist.org/browse/B/Ditrichaceae/Ditrichaceae.csv
      http://www.theplantlist.org/browse/A/Doryanthaceae/Doryanthaceae.csv
      http://www.theplantlist.org/browse/A/Droseraceae/Droseraceae.csv
      http://www.theplantlist.org/browse/A/Drosophyllaceae/Drosophyllaceae.csv
      http://www.theplantlist.org/browse/P/Dryopteridaceae/Dryopteridaceae.csv
      http://www.theplantlist.org/browse/A/Ebenaceae/Ebenaceae.csv
      http://www.theplantlist.org/browse/A/Ecdeiocoleaceae/Ecdeiocoleaceae.csv
      http://www.theplantlist.org/browse/B/Echinodiaceae/Echinodiaceae.csv
      http://www.theplantlist.org/browse/A/Elaeagnaceae/Elaeagnaceae.csv
      http://www.theplantlist.org/browse/A/Elaeocarpaceae/Elaeocarpaceae.csv
      http://www.theplantlist.org/browse/A/Elatinaceae/Elatinaceae.csv
      http://www.theplantlist.org/browse/A/Emblingiaceae/Emblingiaceae.csv
      http://www.theplantlist.org/browse/B/Encalyptaceae/Encalyptaceae.csv
      http://www.theplantlist.org/browse/B/Entodontaceae/Entodontaceae.csv
      http://www.theplantlist.org/browse/G/Ephedraceae/Ephedraceae.csv
      http://www.theplantlist.org/browse/B/Ephemeraceae/Ephemeraceae.csv
      http://www.theplantlist.org/browse/P/Equisetaceae/Equisetaceae.csv
      http://www.theplantlist.org/browse/A/Ericaceae/Ericaceae.csv
      http://www.theplantlist.org/browse/A/Eriocaulaceae/Eriocaulaceae.csv
      http://www.theplantlist.org/browse/B/Erpodiaceae/Erpodiaceae.csv
      http://www.theplantlist.org/browse/A/Erythroxylaceae/Erythroxylaceae.csv
      http://www.theplantlist.org/browse/A/Escalloniaceae/Escalloniaceae.csv
      http://www.theplantlist.org/browse/A/Eucommiaceae/Eucommiaceae.csv
      http://www.theplantlist.org/browse/A/Euphorbiaceae/Euphorbiaceae.csv
      http://www.theplantlist.org/browse/A/Euphroniaceae/Euphroniaceae.csv
      http://www.theplantlist.org/browse/A/Eupomatiaceae/Eupomatiaceae.csv
      http://www.theplantlist.org/browse/A/Eupteleaceae/Eupteleaceae.csv
      http://www.theplantlist.org/browse/B/Eustichiaceae/Eustichiaceae.csv
      http://www.theplantlist.org/browse/B/Exormothecaceae/Exormothecaceae.csv
      http://www.theplantlist.org/browse/B/Fabroniaceae/Fabroniaceae.csv
      http://www.theplantlist.org/browse/A/Fagaceae/Fagaceae.csv
      http://www.theplantlist.org/browse/B/Fissidentaceae/Fissidentaceae.csv
      http://www.theplantlist.org/browse/A/Flagellariaceae/Flagellariaceae.csv
      http://www.theplantlist.org/browse/B/Fontinalaceae/Fontinalaceae.csv
      http://www.theplantlist.org/browse/B/Fontinaliaceae/Fontinaliaceae.csv
      http://www.theplantlist.org/browse/B/Fossombroniaceae/Fossombroniaceae.csv
      http://www.theplantlist.org/browse/A/Fouquieriaceae/Fouquieriaceae.csv
      http://www.theplantlist.org/browse/A/Frankeniaceae/Frankeniaceae.csv
      http://www.theplantlist.org/browse/B/Funariaceae/Funariaceae.csv
      http://www.theplantlist.org/browse/A/Garryaceae/Garryaceae.csv
      http://www.theplantlist.org/browse/A/Geissolomataceae/Geissolomataceae.csv
      http://www.theplantlist.org/browse/A/Gelsemiaceae/Gelsemiaceae.csv
      http://www.theplantlist.org/browse/A/Gentianaceae/Gentianaceae.csv
      http://www.theplantlist.org/browse/B/Geocalycaceae/Geocalycaceae.csv
      http://www.theplantlist.org/browse/A/Geraniaceae/Geraniaceae.csv
      http://www.theplantlist.org/browse/A/Gesneriaceae/Gesneriaceae.csv
      http://www.theplantlist.org/browse/B/Gigaspermaceae/Gigaspermaceae.csv
      http://www.theplantlist.org/browse/G/Ginkgoaceae/Ginkgoaceae.csv
      http://www.theplantlist.org/browse/A/Gisekiaceae/Gisekiaceae.csv
      http://www.theplantlist.org/browse/P/Gleicheniaceae/Gleicheniaceae.csv
      http://www.theplantlist.org/browse/G/Gnetaceae/Gnetaceae.csv
      http://www.theplantlist.org/browse/B/Goebeliellaceae/Goebeliellaceae.csv
      http://www.theplantlist.org/browse/A/Gomortegaceae/Gomortegaceae.csv
      http://www.theplantlist.org/browse/A/Goodeniaceae/Goodeniaceae.csv
      http://www.theplantlist.org/browse/A/Goupiaceae/Goupiaceae.csv
      http://www.theplantlist.org/browse/P/Grammitidaceae/Grammitidaceae.csv
      http://www.theplantlist.org/browse/B/Grimmiaceae/Grimmiaceae.csv
      http://www.theplantlist.org/browse/A/Griseliniaceae/Griseliniaceae.csv
      http://www.theplantlist.org/browse/A/Grossulariaceae/Grossulariaceae.csv
      http://www.theplantlist.org/browse/A/Grubbiaceae/Grubbiaceae.csv
      http://www.theplantlist.org/browse/A/Gunneraceae/Gunneraceae.csv
      http://www.theplantlist.org/browse/B/Gymnomitriaceae/Gymnomitriaceae.csv
      http://www.theplantlist.org/browse/A/Gyrostemonaceae/Gyrostemonaceae.csv
      http://www.theplantlist.org/browse/A/Haemodoraceae/Haemodoraceae.csv
      http://www.theplantlist.org/browse/A/Halophytaceae/Halophytaceae.csv
      http://www.theplantlist.org/browse/A/Haloragaceae/Haloragaceae.csv
      http://www.theplantlist.org/browse/A/Hamamelidaceae/Hamamelidaceae.csv
      http://www.theplantlist.org/browse/A/Hanguanaceae/Hanguanaceae.csv
      http://www.theplantlist.org/browse/B/Haplomitriaceae/Haplomitriaceae.csv
      http://www.theplantlist.org/browse/A/Haptanthaceae/Haptanthaceae.csv
      http://www.theplantlist.org/browse/B/Hedwigiaceae/Hedwigiaceae.csv
      http://www.theplantlist.org/browse/A/Heliconiaceae/Heliconiaceae.csv
      http://www.theplantlist.org/browse/B/Helicophyllaceae/Helicophyllaceae.csv
      http://www.theplantlist.org/browse/A/Helwingiaceae/Helwingiaceae.csv
      http://www.theplantlist.org/browse/B/Herbertaceae/Herbertaceae.csv
      http://www.theplantlist.org/browse/A/Hernandiaceae/Hernandiaceae.csv
      http://www.theplantlist.org/browse/A/Himantandraceae/Himantandraceae.csv
      http://www.theplantlist.org/browse/B/Hookeriaceae/Hookeriaceae.csv
      http://www.theplantlist.org/browse/A/Huaceae/Huaceae.csv
      http://www.theplantlist.org/browse/A/Humiriaceae/Humiriaceae.csv
      http://www.theplantlist.org/browse/A/Hydatellaceae/Hydatellaceae.csv
      http://www.theplantlist.org/browse/A/Hydnoraceae/Hydnoraceae.csv
      http://www.theplantlist.org/browse/A/Hydrangeaceae/Hydrangeaceae.csv
      http://www.theplantlist.org/browse/A/Hydrocharitaceae/Hydrocharitaceae.csv
      http://www.theplantlist.org/browse/A/Hydroleaceae/Hydroleaceae.csv
      http://www.theplantlist.org/browse/A/Hydrostachyaceae/Hydrostachyaceae.csv
      http://www.theplantlist.org/browse/B/Hylocomiaceae/Hylocomiaceae.csv
      http://www.theplantlist.org/browse/P/Hymenophyllaceae/Hymenophyllaceae.csv
      http://www.theplantlist.org/browse/P/Hymenophyllopsidaceae/Hymenophyllopsidaceae.csv
      http://www.theplantlist.org/browse/B/Hymenophytaceae/Hymenophytaceae.csv
      http://www.theplantlist.org/browse/A/Hypericaceae/Hypericaceae.csv
      http://www.theplantlist.org/browse/B/Hypnaceae/Hypnaceae.csv
      http://www.theplantlist.org/browse/B/Hypnodendraceae/Hypnodendraceae.csv
      http://www.theplantlist.org/browse/B/Hypopterygiaceae/Hypopterygiaceae.csv
      http://www.theplantlist.org/browse/A/Hypoxidaceae/Hypoxidaceae.csv
      http://www.theplantlist.org/browse/A/Icacinaceae/Icacinaceae.csv
      http://www.theplantlist.org/browse/A/Iridaceae/Iridaceae.csv
      http://www.theplantlist.org/browse/A/Irvingiaceae/Irvingiaceae.csv
      http://www.theplantlist.org/browse/P/Isoetaceae/Isoetaceae.csv
      http://www.theplantlist.org/browse/A/Iteaceae/Iteaceae.csv
      http://www.theplantlist.org/browse/A/Ixioliriaceae/Ixioliriaceae.csv
      http://www.theplantlist.org/browse/A/Ixonanthaceae/Ixonanthaceae.csv
      http://www.theplantlist.org/browse/B/Jackiellaceae/Jackiellaceae.csv
      http://www.theplantlist.org/browse/A/Joinvilleaceae/Joinvilleaceae.csv
      http://www.theplantlist.org/browse/B/Jubulaceae/Jubulaceae.csv
      http://www.theplantlist.org/browse/B/Jubulopsaceae/Jubulopsaceae.csv
      http://www.theplantlist.org/browse/A/Juglandaceae/Juglandaceae.csv
      http://www.theplantlist.org/browse/A/Juncaceae/Juncaceae.csv
      http://www.theplantlist.org/browse/A/Juncaginaceae/Juncaginaceae.csv
      http://www.theplantlist.org/browse/B/Jungermanniaceae/Jungermanniaceae.csv
      http://www.theplantlist.org/browse/A/Kirkiaceae/Kirkiaceae.csv
      http://www.theplantlist.org/browse/A/Koeberliniaceae/Koeberliniaceae.csv
      http://www.theplantlist.org/browse/A/Krameriaceae/Krameriaceae.csv
      http://www.theplantlist.org/browse/A/Lacistemataceae/Lacistemataceae.csv
      http://www.theplantlist.org/browse/A/Lactoridaceae/Lactoridaceae.csv
      http://www.theplantlist.org/browse/A/Lamiaceae/Lamiaceae.csv
      http://www.theplantlist.org/browse/A/Lanariaceae/Lanariaceae.csv
      http://www.theplantlist.org/browse/A/Lardizabalaceae/Lardizabalaceae.csv
      http://www.theplantlist.org/browse/A/Lauraceae/Lauraceae.csv
      http://www.theplantlist.org/browse/A/Lecythidaceae/Lecythidaceae.csv
      http://www.theplantlist.org/browse/A/Leguminosae/Leguminosae.csv
      http://www.theplantlist.org/browse/B/Lejeuneaceae/Lejeuneaceae.csv
      http://www.theplantlist.org/browse/B/Lembophyllaceae/Lembophyllaceae.csv
      http://www.theplantlist.org/browse/A/Lentibulariaceae/Lentibulariaceae.csv
      http://www.theplantlist.org/browse/B/Lepicoleaceae/Lepicoleaceae.csv
      http://www.theplantlist.org/browse/A/Lepidobotryaceae/Lepidobotryaceae.csv
      http://www.theplantlist.org/browse/B/Lepidolaenaceae/Lepidolaenaceae.csv
      http://www.theplantlist.org/browse/B/Lepidoziaceae/Lepidoziaceae.csv
      http://www.theplantlist.org/browse/B/Leptodontaceae/Leptodontaceae.csv
      http://www.theplantlist.org/browse/B/Lepyrodontaceae/Lepyrodontaceae.csv
      http://www.theplantlist.org/browse/B/Leskeaceae/Leskeaceae.csv
      http://www.theplantlist.org/browse/B/Leucodontaceae/Leucodontaceae.csv
      http://www.theplantlist.org/browse/B/Leucomiaceae/Leucomiaceae.csv
      http://www.theplantlist.org/browse/A/Liliaceae/Liliaceae.csv
      http://www.theplantlist.org/browse/A/Limeaceae/Limeaceae.csv
      http://www.theplantlist.org/browse/A/Limnanthaceae/Limnanthaceae.csv
      http://www.theplantlist.org/browse/A/Linaceae/Linaceae.csv
      http://www.theplantlist.org/browse/A/Linderniaceae/Linderniaceae.csv
      http://www.theplantlist.org/browse/A/Loasaceae/Loasaceae.csv
      http://www.theplantlist.org/browse/A/Loganiaceae/Loganiaceae.csv
      http://www.theplantlist.org/browse/P/Lomariopsidaceae/Lomariopsidaceae.csv
      http://www.theplantlist.org/browse/A/Lophiocarpaceae/Lophiocarpaceae.csv
      http://www.theplantlist.org/browse/B/Lophocoleaceae/Lophocoleaceae.csv
      http://www.theplantlist.org/browse/B/Lophoziaceae/Lophoziaceae.csv
      http://www.theplantlist.org/browse/A/Loranthaceae/Loranthaceae.csv
      http://www.theplantlist.org/browse/A/Lowiaceae/Lowiaceae.csv
      http://www.theplantlist.org/browse/P/Loxsomataceae/Loxsomataceae.csv
      http://www.theplantlist.org/browse/B/Lunulariaceae/Lunulariaceae.csv
      http://www.theplantlist.org/browse/P/Lycopodiaceae/Lycopodiaceae.csv
      http://www.theplantlist.org/browse/A/Lythraceae/Lythraceae.csv
      http://www.theplantlist.org/browse/A/Magnoliaceae/Magnoliaceae.csv
      http://www.theplantlist.org/browse/B/Makinoaceae/Makinoaceae.csv
      http://www.theplantlist.org/browse/A/Malpighiaceae/Malpighiaceae.csv
      http://www.theplantlist.org/browse/A/Malvaceae/Malvaceae.csv
      http://www.theplantlist.org/browse/A/Marantaceae/Marantaceae.csv
      http://www.theplantlist.org/browse/P/Marattiaceae/Marattiaceae.csv
      http://www.theplantlist.org/browse/A/Marcgraviaceae/Marcgraviaceae.csv
      http://www.theplantlist.org/browse/B/Marchantiaceae/Marchantiaceae.csv
      http://www.theplantlist.org/browse/P/Marsileaceae/Marsileaceae.csv
      http://www.theplantlist.org/browse/A/Martyniaceae/Martyniaceae.csv
      http://www.theplantlist.org/browse/B/Mastigophoraceae/Mastigophoraceae.csv
      http://www.theplantlist.org/browse/P/Matoniaceae/Matoniaceae.csv
      http://www.theplantlist.org/browse/A/Mayacaceae/Mayacaceae.csv
      http://www.theplantlist.org/browse/B/Meesiaceae/Meesiaceae.csv
      http://www.theplantlist.org/browse/A/Melanthiaceae/Melanthiaceae.csv
      http://www.theplantlist.org/browse/A/Melastomataceae/Melastomataceae.csv
      http://www.theplantlist.org/browse/A/Meliaceae/Meliaceae.csv
      http://www.theplantlist.org/browse/A/Melianthaceae/Melianthaceae.csv
      http://www.theplantlist.org/browse/A/Menispermaceae/Menispermaceae.csv
      http://www.theplantlist.org/browse/A/Menyanthaceae/Menyanthaceae.csv
      http://www.theplantlist.org/browse/B/Mesoptychiaceae/Mesoptychiaceae.csv
      http://www.theplantlist.org/browse/P/Metaxyaceae/Metaxyaceae.csv
      http://www.theplantlist.org/browse/B/Meteoriaceae/Meteoriaceae.csv
      http://www.theplantlist.org/browse/A/Metteniusaceae/Metteniusaceae.csv
      http://www.theplantlist.org/browse/B/Metzgeriaceae/Metzgeriaceae.csv
      http://www.theplantlist.org/browse/A/Misodendraceae/Misodendraceae.csv
      http://www.theplantlist.org/browse/A/Mitrastemonaceae/Mitrastemonaceae.csv
      http://www.theplantlist.org/browse/B/Mitteniaceae/Mitteniaceae.csv
      http://www.theplantlist.org/browse/B/Mniaceae/Mniaceae.csv
      http://www.theplantlist.org/browse/A/Molluginaceae/Molluginaceae.csv
      http://www.theplantlist.org/browse/A/Monimiaceae/Monimiaceae.csv
      http://www.theplantlist.org/browse/B/Monocarpaceae/Monocarpaceae.csv
      http://www.theplantlist.org/browse/A/Montiaceae/Montiaceae.csv
      http://www.theplantlist.org/browse/A/Montiniaceae/Montiniaceae.csv
      http://www.theplantlist.org/browse/A/Moraceae/Moraceae.csv
      http://www.theplantlist.org/browse/A/Moringaceae/Moringaceae.csv
      http://www.theplantlist.org/browse/A/Muntingiaceae/Muntingiaceae.csv
      http://www.theplantlist.org/browse/A/Musaceae/Musaceae.csv
      http://www.theplantlist.org/browse/B/Myliaceae/Myliaceae.csv
      http://www.theplantlist.org/browse/A/Myodocarpaceae/Myodocarpaceae.csv
      http://www.theplantlist.org/browse/A/Myricaceae/Myricaceae.csv
      http://www.theplantlist.org/browse/B/Myriniaceae/Myriniaceae.csv
      http://www.theplantlist.org/browse/A/Myristicaceae/Myristicaceae.csv
      http://www.theplantlist.org/browse/A/Myrothamnaceae/Myrothamnaceae.csv
      http://www.theplantlist.org/browse/A/Myrtaceae/Myrtaceae.csv
      http://www.theplantlist.org/browse/B/Myuriaceae/Myuriaceae.csv
      http://www.theplantlist.org/browse/A/Nartheciaceae/Nartheciaceae.csv
      http://www.theplantlist.org/browse/B/Neckeraceae/Neckeraceae.csv
      http://www.theplantlist.org/browse/A/Nelumbonaceae/Nelumbonaceae.csv
      http://www.theplantlist.org/browse/B/Neotrichocoleaceae/Neotrichocoleaceae.csv
      http://www.theplantlist.org/browse/A/Nepenthaceae/Nepenthaceae.csv
      http://www.theplantlist.org/browse/A/Neuradaceae/Neuradaceae.csv
      http://www.theplantlist.org/browse/A/Nitrariaceae/Nitrariaceae.csv
      http://www.theplantlist.org/browse/A/Nothofagaceae/Nothofagaceae.csv
      http://www.theplantlist.org/browse/B/Notothyladaceae/Notothyladaceae.csv
      http://www.theplantlist.org/browse/A/Nyctaginaceae/Nyctaginaceae.csv
      http://www.theplantlist.org/browse/A/Nymphaeaceae/Nymphaeaceae.csv
      http://www.theplantlist.org/browse/A/Ochnaceae/Ochnaceae.csv
      http://www.theplantlist.org/browse/B/Octoblepharaceae/Octoblepharaceae.csv
      http://www.theplantlist.org/browse/B/Oedipodiaceae/Oedipodiaceae.csv
      http://www.theplantlist.org/browse/A/Olacaceae/Olacaceae.csv
      http://www.theplantlist.org/browse/A/Oleaceae/Oleaceae.csv
      http://www.theplantlist.org/browse/P/Oleandraceae/Oleandraceae.csv
      http://www.theplantlist.org/browse/A/Onagraceae/Onagraceae.csv
      http://www.theplantlist.org/browse/A/Oncothecaceae/Oncothecaceae.csv
      http://www.theplantlist.org/browse/P/Ophioglossaceae/Ophioglossaceae.csv
      http://www.theplantlist.org/browse/A/Opiliaceae/Opiliaceae.csv
      http://www.theplantlist.org/browse/A/Orchidaceae/Orchidaceae.csv
      http://www.theplantlist.org/browse/A/Orobanchaceae/Orobanchaceae.csv
      http://www.theplantlist.org/browse/B/Orthorrhynchiaceae/Orthorrhynchiaceae.csv
      http://www.theplantlist.org/browse/B/Orthotrichaceae/Orthotrichaceae.csv
      http://www.theplantlist.org/browse/P/Osmundaceae/Osmundaceae.csv
      http://www.theplantlist.org/browse/A/Oxalidaceae/Oxalidaceae.csv
      http://www.theplantlist.org/browse/B/Oxymitraceae/Oxymitraceae.csv
      http://www.theplantlist.org/browse/A/Paeoniaceae/Paeoniaceae.csv
      http://www.theplantlist.org/browse/B/Pallaviciniaceae/Pallaviciniaceae.csv
      http://www.theplantlist.org/browse/A/Pandaceae/Pandaceae.csv
      http://www.theplantlist.org/browse/A/Pandanaceae/Pandanaceae.csv
      http://www.theplantlist.org/browse/A/Papaveraceae/Papaveraceae.csv
      http://www.theplantlist.org/browse/A/Paracryphiaceae/Paracryphiaceae.csv
      http://www.theplantlist.org/browse/A/Passifloraceae/Passifloraceae.csv
      http://www.theplantlist.org/browse/A/Paulowniaceae/Paulowniaceae.csv
      http://www.theplantlist.org/browse/A/Pedaliaceae/Pedaliaceae.csv
      http://www.theplantlist.org/browse/B/Pelliaceae/Pelliaceae.csv
      http://www.theplantlist.org/browse/A/Penaeaceae/Penaeaceae.csv
      http://www.theplantlist.org/browse/A/Pentadiplandraceae/Pentadiplandraceae.csv
      http://www.theplantlist.org/browse/A/Pentaphragmataceae/Pentaphragmataceae.csv
      http://www.theplantlist.org/browse/A/Pentaphylacaceae/Pentaphylacaceae.csv
      http://www.theplantlist.org/browse/A/Penthoraceae/Penthoraceae.csv
      http://www.theplantlist.org/browse/A/Peraceae/Peraceae.csv
      http://www.theplantlist.org/browse/A/Peridiscaceae/Peridiscaceae.csv
      http://www.theplantlist.org/browse/A/Petermanniaceae/Petermanniaceae.csv
      http://www.theplantlist.org/browse/A/Petrosaviaceae/Petrosaviaceae.csv
      http://www.theplantlist.org/browse/A/Philesiaceae/Philesiaceae.csv
      http://www.theplantlist.org/browse/A/Philydraceae/Philydraceae.csv
      http://www.theplantlist.org/browse/A/Phrymaceae/Phrymaceae.csv
      http://www.theplantlist.org/browse/A/Phyllanthaceae/Phyllanthaceae.csv
      http://www.theplantlist.org/browse/B/Phyllodrepaniaceae/Phyllodrepaniaceae.csv
      http://www.theplantlist.org/browse/B/Phyllogoniaceae/Phyllogoniaceae.csv
      http://www.theplantlist.org/browse/A/Phyllonomaceae/Phyllonomaceae.csv
      http://www.theplantlist.org/browse/A/Physenaceae/Physenaceae.csv
      http://www.theplantlist.org/browse/A/Phytolaccaceae/Phytolaccaceae.csv
      http://www.theplantlist.org/browse/A/Picramniaceae/Picramniaceae.csv
      http://www.theplantlist.org/browse/A/Picrodendraceae/Picrodendraceae.csv
      http://www.theplantlist.org/browse/B/Pilotrichaceae/Pilotrichaceae.csv
      http://www.theplantlist.org/browse/G/Pinaceae/Pinaceae.csv
      http://www.theplantlist.org/browse/A/Piperaceae/Piperaceae.csv
      http://www.theplantlist.org/browse/A/Pittosporaceae/Pittosporaceae.csv
      http://www.theplantlist.org/browse/B/Plagiochilaceae/Plagiochilaceae.csv
      http://www.theplantlist.org/browse/P/Plagiogyriaceae/Plagiogyriaceae.csv
      http://www.theplantlist.org/browse/B/Plagiotheciaceae/Plagiotheciaceae.csv
      http://www.theplantlist.org/browse/A/Plantaginaceae/Plantaginaceae.csv
      http://www.theplantlist.org/browse/A/Platanaceae/Platanaceae.csv
      http://www.theplantlist.org/browse/B/Pleuroziaceae/Pleuroziaceae.csv
      http://www.theplantlist.org/browse/B/Pleuroziopsaceae/Pleuroziopsaceae.csv
      http://www.theplantlist.org/browse/A/Plocospermataceae/Plocospermataceae.csv
      http://www.theplantlist.org/browse/A/Plumbaginaceae/Plumbaginaceae.csv
      http://www.theplantlist.org/browse/A/Poaceae/Poaceae.csv
      http://www.theplantlist.org/browse/G/Podocarpaceae/Podocarpaceae.csv
      http://www.theplantlist.org/browse/A/Podostemaceae/Podostemaceae.csv
      http://www.theplantlist.org/browse/A/Polemoniaceae/Polemoniaceae.csv
      http://www.theplantlist.org/browse/A/Polygalaceae/Polygalaceae.csv
      http://www.theplantlist.org/browse/A/Polygonaceae/Polygonaceae.csv
      http://www.theplantlist.org/browse/P/Polypodiaceae/Polypodiaceae.csv
      http://www.theplantlist.org/browse/B/Polytrichaceae/Polytrichaceae.csv
      http://www.theplantlist.org/browse/A/Pontederiaceae/Pontederiaceae.csv
      http://www.theplantlist.org/browse/B/Porellaceae/Porellaceae.csv
      http://www.theplantlist.org/browse/A/Portulacaceae/Portulacaceae.csv
      http://www.theplantlist.org/browse/A/Posidoniaceae/Posidoniaceae.csv
      http://www.theplantlist.org/browse/A/Potamogetonaceae/Potamogetonaceae.csv
      http://www.theplantlist.org/browse/B/Pottiaceae/Pottiaceae.csv
      http://www.theplantlist.org/browse/A/Primulaceae/Primulaceae.csv
      http://www.theplantlist.org/browse/B/Prionodontaceae/Prionodontaceae.csv
      http://www.theplantlist.org/browse/A/Proteaceae/Proteaceae.csv
      http://www.theplantlist.org/browse/B/Pseudolepicoleaceae/Pseudolepicoleaceae.csv
      http://www.theplantlist.org/browse/P/Psilotaceae/Psilotaceae.csv
      http://www.theplantlist.org/browse/P/Pteridaceae/Pteridaceae.csv
      http://www.theplantlist.org/browse/B/Pterigynandraceae/Pterigynandraceae.csv
      http://www.theplantlist.org/browse/B/Pterobryaceae/Pterobryaceae.csv
      http://www.theplantlist.org/browse/B/Ptilidiaceae/Ptilidiaceae.csv
      http://www.theplantlist.org/browse/B/Ptychomitriaceae/Ptychomitriaceae.csv
      http://www.theplantlist.org/browse/B/Ptychomniaceae/Ptychomniaceae.csv
      http://www.theplantlist.org/browse/A/Putranjivaceae/Putranjivaceae.csv
      http://www.theplantlist.org/browse/A/Quillajaceae/Quillajaceae.csv
      http://www.theplantlist.org/browse/B/Racopilaceae/Racopilaceae.csv
      http://www.theplantlist.org/browse/B/Radulaceae/Radulaceae.csv
      http://www.theplantlist.org/browse/A/Rafflesiaceae/Rafflesiaceae.csv
      http://www.theplantlist.org/browse/A/Ranunculaceae/Ranunculaceae.csv
      http://www.theplantlist.org/browse/A/Rapateaceae/Rapateaceae.csv
      http://www.theplantlist.org/browse/B/Regmatodontaceae/Regmatodontaceae.csv
      http://www.theplantlist.org/browse/A/Resedaceae/Resedaceae.csv
      http://www.theplantlist.org/browse/A/Restionaceae/Restionaceae.csv
      http://www.theplantlist.org/browse/A/Rhabdodendraceae/Rhabdodendraceae.csv
      http://www.theplantlist.org/browse/B/Rhabdoweisiaceae/Rhabdoweisiaceae.csv
      http://www.theplantlist.org/browse/B/Rhachitheciaceae/Rhachitheciaceae.csv
      http://www.theplantlist.org/browse/B/Rhacocarpaceae/Rhacocarpaceae.csv
      http://www.theplantlist.org/browse/A/Rhamnaceae/Rhamnaceae.csv
      http://www.theplantlist.org/browse/A/Rhipogonaceae/Rhipogonaceae.csv
      http://www.theplantlist.org/browse/B/Rhizogoniaceae/Rhizogoniaceae.csv
      http://www.theplantlist.org/browse/A/Rhizophoraceae/Rhizophoraceae.csv
      http://www.theplantlist.org/browse/B/Ricciaceae/Ricciaceae.csv
      http://www.theplantlist.org/browse/B/Riellaceae/Riellaceae.csv
      http://www.theplantlist.org/browse/B/Rigodiaceae/Rigodiaceae.csv
      http://www.theplantlist.org/browse/A/Roridulaceae/Roridulaceae.csv
      http://www.theplantlist.org/browse/A/Rosaceae/Rosaceae.csv
      http://www.theplantlist.org/browse/A/Rousseaceae/Rousseaceae.csv
      http://www.theplantlist.org/browse/A/Rubiaceae/Rubiaceae.csv
      http://www.theplantlist.org/browse/A/Ruppiaceae/Ruppiaceae.csv
      http://www.theplantlist.org/browse/A/Rutaceae/Rutaceae.csv
      http://www.theplantlist.org/browse/B/Rutenbergiaceae/Rutenbergiaceae.csv
      http://www.theplantlist.org/browse/A/Sabiaceae/Sabiaceae.csv
      http://www.theplantlist.org/browse/A/Salicaceae/Salicaceae.csv
      http://www.theplantlist.org/browse/A/Salvadoraceae/Salvadoraceae.csv
      http://www.theplantlist.org/browse/P/Salviniaceae/Salviniaceae.csv
      http://www.theplantlist.org/browse/A/Santalaceae/Santalaceae.csv
      http://www.theplantlist.org/browse/A/Sapindaceae/Sapindaceae.csv
      http://www.theplantlist.org/browse/A/Sapotaceae/Sapotaceae.csv
      http://www.theplantlist.org/browse/A/Sarcobataceae/Sarcobataceae.csv
      http://www.theplantlist.org/browse/A/Sarcolaenaceae/Sarcolaenaceae.csv
      http://www.theplantlist.org/browse/A/Sarraceniaceae/Sarraceniaceae.csv
      http://www.theplantlist.org/browse/A/Saururaceae/Saururaceae.csv
      http://www.theplantlist.org/browse/A/Saxifragaceae/Saxifragaceae.csv
      http://www.theplantlist.org/browse/B/Scapaniaceae/Scapaniaceae.csv
      http://www.theplantlist.org/browse/A/Scheuchzeriaceae/Scheuchzeriaceae.csv
      http://www.theplantlist.org/browse/A/Schisandraceae/Schisandraceae.csv
      http://www.theplantlist.org/browse/B/Schistochilaceae/Schistochilaceae.csv
      http://www.theplantlist.org/browse/B/Schistostegaceae/Schistostegaceae.csv
      http://www.theplantlist.org/browse/P/Schizaeaceae/Schizaeaceae.csv
      http://www.theplantlist.org/browse/A/Schlegeliaceae/Schlegeliaceae.csv
      http://www.theplantlist.org/browse/A/Schoepfiaceae/Schoepfiaceae.csv
      http://www.theplantlist.org/browse/B/Scorpidiaceae/Scorpidiaceae.csv
      http://www.theplantlist.org/browse/A/Scrophulariaceae/Scrophulariaceae.csv
      http://www.theplantlist.org/browse/P/Selaginellaceae/Selaginellaceae.csv
      http://www.theplantlist.org/browse/B/Seligeriaceae/Seligeriaceae.csv
      http://www.theplantlist.org/browse/B/Sematophyllaceae/Sematophyllaceae.csv
      http://www.theplantlist.org/browse/B/Serpotortellaceae/Serpotortellaceae.csv
      http://www.theplantlist.org/browse/A/Setchellanthaceae/Setchellanthaceae.csv
      http://www.theplantlist.org/browse/A/Simaroubaceae/Simaroubaceae.csv
      http://www.theplantlist.org/browse/A/Simmondsiaceae/Simmondsiaceae.csv
      http://www.theplantlist.org/browse/A/Siparunaceae/Siparunaceae.csv
      http://www.theplantlist.org/browse/A/Sladeniaceae/Sladeniaceae.csv
      http://www.theplantlist.org/browse/A/Smilacaceae/Smilacaceae.csv
      http://www.theplantlist.org/browse/A/Solanaceae/Solanaceae.csv
      http://www.theplantlist.org/browse/A/Sphaerosepalaceae/Sphaerosepalaceae.csv
      http://www.theplantlist.org/browse/B/Sphagnaceae/Sphagnaceae.csv
      http://www.theplantlist.org/browse/A/Sphenocleaceae/Sphenocleaceae.csv
      http://www.theplantlist.org/browse/B/Spiridentaceae/Spiridentaceae.csv
      http://www.theplantlist.org/browse/B/Splachnaceae/Splachnaceae.csv
      http://www.theplantlist.org/browse/B/Splachnobryaceae/Splachnobryaceae.csv
      http://www.theplantlist.org/browse/A/Stachyuraceae/Stachyuraceae.csv
      http://www.theplantlist.org/browse/A/Staphyleaceae/Staphyleaceae.csv
      http://www.theplantlist.org/browse/A/Stegnospermataceae/Stegnospermataceae.csv
      http://www.theplantlist.org/browse/A/Stemonaceae/Stemonaceae.csv
      http://www.theplantlist.org/browse/A/Stemonuraceae/Stemonuraceae.csv
      http://www.theplantlist.org/browse/B/Stereophyllaceae/Stereophyllaceae.csv
      http://www.theplantlist.org/browse/A/Stilbaceae/Stilbaceae.csv
      http://www.theplantlist.org/browse/A/Strasburgeriaceae/Strasburgeriaceae.csv
      http://www.theplantlist.org/browse/A/Strelitziaceae/Strelitziaceae.csv
      http://www.theplantlist.org/browse/A/Stylidiaceae/Stylidiaceae.csv
      http://www.theplantlist.org/browse/A/Styracaceae/Styracaceae.csv
      http://www.theplantlist.org/browse/A/Surianaceae/Surianaceae.csv
      http://www.theplantlist.org/browse/A/Symplocaceae/Symplocaceae.csv
      http://www.theplantlist.org/browse/B/Takakiaceae/Takakiaceae.csv
      http://www.theplantlist.org/browse/A/Talinaceae/Talinaceae.csv
      http://www.theplantlist.org/browse/A/Tamaricaceae/Tamaricaceae.csv
      http://www.theplantlist.org/browse/A/Tapisciaceae/Tapisciaceae.csv
      http://www.theplantlist.org/browse/B/Targioniaceae/Targioniaceae.csv
      http://www.theplantlist.org/browse/G/Taxaceae/Taxaceae.csv
      http://www.theplantlist.org/browse/G/Taxodiaceae/Taxodiaceae.csv
      http://www.theplantlist.org/browse/A/Tecophilaeaceae/Tecophilaeaceae.csv
      http://www.theplantlist.org/browse/A/Tetrachondraceae/Tetrachondraceae.csv
      http://www.theplantlist.org/browse/A/Tetramelaceae/Tetramelaceae.csv
      http://www.theplantlist.org/browse/A/Tetrameristaceae/Tetrameristaceae.csv
      http://www.theplantlist.org/browse/B/Tetraphidaceae/Tetraphidaceae.csv
      http://www.theplantlist.org/browse/B/Thamnobryaceae/Thamnobryaceae.csv
      http://www.theplantlist.org/browse/A/Theaceae/Theaceae.csv
      http://www.theplantlist.org/browse/B/Theliaceae/Theliaceae.csv
      http://www.theplantlist.org/browse/P/Thelypteridaceae/Thelypteridaceae.csv
      http://www.theplantlist.org/browse/A/Thomandersiaceae/Thomandersiaceae.csv
      http://www.theplantlist.org/browse/B/Thuidiaceae/Thuidiaceae.csv
      http://www.theplantlist.org/browse/A/Thurniaceae/Thurniaceae.csv
      http://www.theplantlist.org/browse/A/Thymelaeaceae/Thymelaeaceae.csv
      http://www.theplantlist.org/browse/A/Ticodendraceae/Ticodendraceae.csv
      http://www.theplantlist.org/browse/B/Timmiaceae/Timmiaceae.csv
      http://www.theplantlist.org/browse/A/Tofieldiaceae/Tofieldiaceae.csv
      http://www.theplantlist.org/browse/A/Torricelliaceae/Torricelliaceae.csv
      http://www.theplantlist.org/browse/A/Tovariaceae/Tovariaceae.csv
      http://www.theplantlist.org/browse/B/Trachypodaceae/Trachypodaceae.csv
      http://www.theplantlist.org/browse/B/Treubiaceae/Treubiaceae.csv
      http://www.theplantlist.org/browse/B/Trichocoleaceae/Trichocoleaceae.csv
      http://www.theplantlist.org/browse/A/Trigoniaceae/Trigoniaceae.csv
      http://www.theplantlist.org/browse/A/Triuridaceae/Triuridaceae.csv
      http://www.theplantlist.org/browse/A/Trochodendraceae/Trochodendraceae.csv
      http://www.theplantlist.org/browse/A/Tropaeolaceae/Tropaeolaceae.csv
      http://www.theplantlist.org/browse/A/Typhaceae/Typhaceae.csv
      http://www.theplantlist.org/browse/A/Ulmaceae/Ulmaceae.csv
      http://www.theplantlist.org/browse/A/Urticaceae/Urticaceae.csv
      http://www.theplantlist.org/browse/A/Vahliaceae/Vahliaceae.csv
      http://www.theplantlist.org/browse/A/Velloziaceae/Velloziaceae.csv
      http://www.theplantlist.org/browse/A/Verbenaceae/Verbenaceae.csv
      http://www.theplantlist.org/browse/B/Vetaformaceae/Vetaformaceae.csv
      http://www.theplantlist.org/browse/A/Violaceae/Violaceae.csv
      http://www.theplantlist.org/browse/A/Vitaceae/Vitaceae.csv
      http://www.theplantlist.org/browse/P/Vittariaceae/Vittariaceae.csv
      http://www.theplantlist.org/browse/A/Vivianiaceae/Vivianiaceae.csv
      http://www.theplantlist.org/browse/A/Vochysiaceae/Vochysiaceae.csv
      http://www.theplantlist.org/browse/B/Wardiaceae/Wardiaceae.csv
      http://www.theplantlist.org/browse/G/Welwitschiaceae/Welwitschiaceae.csv
      http://www.theplantlist.org/browse/B/Wiesnerellaceae/Wiesnerellaceae.csv
      http://www.theplantlist.org/browse/A/Winteraceae/Winteraceae.csv
      http://www.theplantlist.org/browse/P/Woodsiaceae/Woodsiaceae.csv
      http://www.theplantlist.org/browse/A/Xanthorrhoeaceae/Xanthorrhoeaceae.csv
      http://www.theplantlist.org/browse/A/Xeronemataceae/Xeronemataceae.csv
      http://www.theplantlist.org/browse/A/Xyridaceae/Xyridaceae.csv
      http://www.theplantlist.org/browse/G/Zamiaceae/Zamiaceae.csv
      http://www.theplantlist.org/browse/A/Zingiberaceae/Zingiberaceae.csv
      http://www.theplantlist.org/browse/A/Zosteraceae/Zosteraceae.csv
      http://www.theplantlist.org/browse/A/Zygophyllaceae/Zygophyllaceae.csv
    ).each do |url|
      filename = url.match(/\/[A-Z]\/([A-Za-z]*)\/(.*)\z/)[2]
      puts "Fetching #{filename} ..."
      open(Rails.root + "tmp/plant_list/#{filename}", 'wb') do |file|
        file << open(url).read
      end
    end
  end
end
