# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d15ae1498c3b1093fddcdafe6742084d8e45a3adb24abeb8d9f4ceff1df97af96e7e1ae7ed0df4aae6a42caea49500baf1d0321f7aca9d38e5476a5652644043

test:
  secret_key_base: 872961c4236e9b45b0a7f7dfe87f63cbdd76b036e3e3ab9fd78c6a4617cc5236ecc88b40fadb07ea9d8d44d5cb94702a7e05900c480033c86013ea0f3050d5b6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
